
\copy account_permission FROM '../../flat_out/AccountPermission.txt' DELIMITER '|'
\copy customer FROM '../../flat_out/Customer.txt' DELIMITER '|'
\copy customer_account FROM '../../flat_out/CustomerAccount.txt' DELIMITER '|'
\copy customer_taxrate FROM '../../flat_out/CustomerTaxrate.txt' DELIMITER '|'
\copy holding FROM '../../flat_out/Holding.txt' DELIMITER '|'
\copy holding_history FROM '../../flat_out/HoldingHistory.txt' DELIMITER '|'
\copy holding_summary FROM '../../flat_out/HoldingSummary.txt' DELIMITER '|'
\copy watch_item FROM '../../flat_out/WatchItem.txt' DELIMITER '|'
\copy watch_list FROM '../../flat_out/WatchList.txt' DELIMITER '|'
\copy broker FROM '../../flat_out/Broker.txt' DELIMITER '|'
\copy cash_transaction FROM '../../flat_out/CashTransaction.txt' DELIMITER '|'
\copy charge FROM '../../flat_out/Charge.txt' DELIMITER '|'
\copy commission_rate FROM '../../flat_out/CommissionRate.txt' DELIMITER '|'
\copy settlement FROM '../../flat_out/Settlement.txt' DELIMITER '|'
\copy trade FROM '../../flat_out/Trade.txt' DELIMITER '|'
\copy trade_history FROM '../../flat_out/TradeHistory.txt' DELIMITER '|'
-- \copy trade_request FROM '../../flat_out/TradeRequest.txt' DELIMITER '|'
\copy trade_type FROM '../../flat_out/TradeType.txt' DELIMITER '|'
\copy company FROM '../../flat_out/Company.txt' DELIMITER '|'
\copy company_competitor FROM '../../flat_out/CompanyCompetitor.txt' DELIMITER '|'
\copy daily_market FROM '../../flat_out/DailyMarket.txt' DELIMITER '|'
\copy exchange FROM '../../flat_out/Exchange.txt' DELIMITER '|'
\copy financial FROM '../../flat_out/Financial.txt' DELIMITER '|'
\copy industry FROM '../../flat_out/Industry.txt' DELIMITER '|'
\copy last_trade FROM '../../flat_out/LastTrade.txt' DELIMITER '|'
\copy news_item FROM '../../flat_out/NewsItem.txt' DELIMITER '|'
\copy news_xref FROM '../../flat_out/NewsXRef.txt' DELIMITER '|'
\copy sector FROM '../../flat_out/Sector.txt' DELIMITER '|'
\copy security FROM '../../flat_out/Security.txt' DELIMITER '|'
\copy address FROM '../../flat_out/Address.txt' DELIMITER '|'
\copy status_type FROM '../../flat_out/StatusType.txt' DELIMITER '|'
\copy taxrate FROM '../../flat_out/Taxrate.txt' DELIMITER '|'
\copy zip_code FROM '../../flat_out/ZipCode.txt' DELIMITER '|'

